### ISSUE TITLE
Pause/Resume not working

### ISSUE THREAD

**Issue by vPrapo** [ludufre/xmworkers#1]
**Thank you very much for the nice work!**

I'm only having a problem in pausing and resuming
it shows success but nothing happens.

**Response**
```
{
    "error": {
        "code": -32700,
        "message": "Parse error"
    },
    "jsonrpc": "2.0",
    "id": null
}
```

the **Request** shown as

```
[object Object]
```

I couldn't figure out how to fix it.

**Comment by ludufre** [comment]
What is the version of XMrig?
