### ISSUE TITLE
Your product implementation

### ISSUE THREAD

**Issue by vpts1202** [ludufre/xmworkers#3]
Hello Good Man @ludufre.
Thank you for Enhancement you have done, its very kind.
-	Should I add my workers IPs into “URL” string(or to "Import" string?) at http://xmworkers.ludufre.com/? 
-	How it should be separated? By commas, or underscore, etc?
-	What are the maximum IPs/Workers I can add in one time?

Once again many thanks for your work and for your kind approach.
PS::  I couldn’t find in any of your repos donation wallet. Please provide-good deeds should be returned with gratitude

**Comment by ludufre** [comment]
Like this

![image](https://user-images.githubusercontent.com/4112077/137520832-b123f899-66a9-4aa0-b9a0-1314b25ff629.png)

You can use my hosted version, or host yourself. 

There is no limit depending on your computer's capabilities. Here I use 30 workers with no problems.

**Comment by vpts1202** [comment]
Thank you for your prompt and useful feedback.
Last question please regarding to ports: Any ISPs are unpredictable from any technical issue up to simple human factor. So some ports might be simply closed. In order to avoid any guessing if I will place into config  port random choice(“0”) will it work then? If it will work then should I add new worker like this: http://192.168.0.100:0 ?

Or you still would advise to place certain port?

Surely I will use your hosted version (why don’t you place your donation address?)
Once again thank you for your great work and your kind assistance.

**Comment by ludufre** [comment]
> In order to avoid any guessing if I will place into config port random choice(“0”) will it work then?

No, you must provide and make sure that port is open.

>Surely I will use your hosted version (why don’t you place your donation address?)

A while ago, I wanted to develop new features on the [original dashboard](http://workers.xmrig.info/). As the source code was not public, I reverse engineered it and recreated it. The original is now public on https://github.com/xmrig/xmrig-workers
For that reason I can't receive donations, since this is not my original idea.

**Comment by vpts1202** [comment]
Got you.
Many thanks for your great work.
