### ISSUE TITLE
Instructions for self-hosting

### ISSUE THREAD

**Issue by AntlerDM** [ludufre/xmworkers#6]
I have been self hosting the original XMWorkers for a while now and would like to switch it to your version for the added functionality. But I cannot figure out how to do that. 

Do you have instructions somewhere that would help?

**Comment by ludufre** [comment]
I'm sorry. I completely forgot about it. This weekend I will write in detail how to host.

**Comment by AntlerDM** [comment]
Any progress with this?

I tried to build with the instructions in the readme but I was not successful.

**Comment by ludufre** [comment]
Hi @AntlerDM, sorry for the delay. I don't use this anymore...

Here is the compiled code. You'll need to host with Nginx, Apache or equivalent. Remember to host as HTTP (not HTTPS) because of CORS.

https://github.com/ludufre/xmworkers/releases

**Comment by AntlerDM** [comment]
Thank you. That works great.

**Comment by AntlerDM** [comment]
I have run into a small issue and wonder if you might have a solution.

When I go to the page initially (eg. http...workers.myserver.com:1234/) it loads correctly. The url is changed to http...workers.myserver.com:1234/dashboard. If I reload the page, I get a "Not Found. The requested URL was not found on this server." error. Removing the "dashboard" from the url allows it to load correctly.

Do you have any suggestions on how I might fix this?

**Comment by ludufre** [comment]
If you use Nginx use something like this:

```
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {
        listen 80;
        server_name  localhost;

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        include /etc/nginx/mime.types;

        gzip on;
        gzip_min_length 1000;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
```

Or Apache, add this to httpd.conf:

```
<Directory "D:/ApacheAngular/dist/ApacheAngular">
FallbackResource ./index.html
Options Indexes FollowSymLinks
AllowOverride None
Require all granted
</Directory>
```

**Comment by AntlerDM** [comment]
Thank you.

Adding the fallback directive on apache worked.
