### ISSUE TITLE
Connection to your host

### ISSUE THREAD

**Issue by vpts1202** [ludufre/xmworkers#8]
Hello
I have tried to connect to your host via Tor browser. HTTPS-only mode was disabled, however I couldn’t get in. Then I have tried the option of placing your domain (xmworkers.ludufre.com) into exception and I couldn’t get in either.

How to sort it out?
Thanks

**Comment by ludufre** [comment]
I don't know about Tor's behavior, but I know that the HTTP address is working: ![image](https://github.com/ludufre/xmworkers/assets/4112077/a0881e39-fbe5-4b0f-bdf6-e2d4c783757b)
